import json
from pathlib import Path
import shutil


# Stores all changes as: (json_path, old_value, new_value, file)
DIFF_LOG = []


def recursive_update(new_data, old_data, path="", file_name=""):
    """
    Recursively updates NEW data from OLD data.
    Logs differences along the way.
    """

    #merging dicts
    if isinstance(old_data, dict) and isinstance(new_data, dict):
        for key, old_value in old_data.items():
            if key in new_data:
                current_path = f"{path}.{key}" if path else key
                new_data[key] = recursive_update(
                    new_data[key],
                    old_value,
                    current_path,
                    file_name
                )
        return new_data

    #merging lists
    if isinstance(old_data, list) and isinstance(new_data, list):
        updated_list = new_data[:]

        for i in range(min(len(old_data), len(new_data))):
            if isinstance(old_data[i], dict) and isinstance(new_data[i], dict):
                current_path = f"{path}[{i}]"
                updated_list[i] = recursive_update(
                    new_data[i],
                    old_data[i],
                    current_path,
                    file_name
                )
        return updated_list

    #primitive value replaced
    if new_data != old_data:
        DIFF_LOG.append((path, old_data, new_data, file_name))

    return old_data



def update_json_file(old_path, new_path, output_path):
    with open(old_path, "r", encoding="utf-8") as f:
        old_json = json.load(f)

    with open(new_path, "r", encoding="utf-8") as f:
        new_json = json.load(f)

    # Run update with the file name known
    updated = recursive_update(new_json, old_json, path="", file_name=str(new_path))

    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(updated, f, indent=4)



def update_folder(old_folder, new_folder, output_folder):
    old_folder = Path(old_folder)
    new_folder = Path(new_folder)
    output_folder = Path(output_folder)

    for new_file in new_folder.rglob("*.json"):
        relative = new_file.relative_to(new_folder)
        output_file = output_folder / relative

        # Skip Info.json
        if new_file.name.lower() == "info.json":
            print(f"Skipping Info.json: {relative}")
            output_file.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(new_file, output_file)
            continue

        old_file = old_folder / relative

        if old_file.exists():
            print(f"Updating: {relative}")
            update_json_file(old_file, new_file, output_file)
        else:
            print(f"Copying new-only file: {relative}")
            output_file.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(new_file, output_file)

    print("\n✔ All configs processed.")
    print("✔ Updated files saved to:", output_folder)



def write_diff_log(output_folder, filename="diff_log.txt"):
    """
    Save diff log to a text file.
    """

    output_path = Path(output_folder) / filename

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("====== CONFIG DIFFERENCE LOG ======\n")
        f.write("Generated by SAIN updater\n\n")

        if not DIFF_LOG:
            f.write("No differences found.\n")
            return

        for path, old_val, new_val, file_name in DIFF_LOG:
            f.write(f"[FILE] {file_name}\n")
            f.write(f"[SECTION] {path}\n")
            f.write(f"  OLD: {old_val}\n")
            f.write(f"  NEW: {new_val}\n\n")

    print(f"\n✔ Difference log written to: {output_path}")


def print_diff_console():
    """
    Print diffs to the terminal.
    """
    print("\n==================== CHANGES DETECTED ====================\n")

    if not DIFF_LOG:
        print("No differences found.")
        return

    for path, old_val, new_val, file_name in DIFF_LOG:
        print(f"[{file_name}] {path}")
        print(f"   Old: {old_val}")
        print(f"   New: {new_val}\n")



if __name__ == "__main__":
    import sys

    if len(sys.argv) < 4:
        print("Usage: python sainupdater.py <old_folder> <new_folder> <output_folder>")
        sys.exit(1)

    old_folder = sys.argv[1]
    new_folder = sys.argv[2]
    output_folder = sys.argv[3]

    update_folder(old_folder, new_folder, output_folder)

    # Print to console
    print_diff_console()

    # Write to a file
    write_diff_log(output_folder, "diff_log.txt")
